import coronet_data from '../coronet_generated_files/Encounter_output.json';
type EncounterTable = {[key in string]: string[]}

const staticEncounters: EncounterTable = {
  'coro-0': ['Turtwig', 'Chimchar', 'Piplup'],
  'coro-1': ['Eevee'],
  'coro-3': ['Eevee'],
  'coro-4': [
    // Trainer School Egg has every baby here
    'Pichu',
    'Cleffa',
    'Igglybuff',
    'Smoochum',
    'Tyrogue',
    'Smoochum',
    'Elekid',
    'Magby',
    'Azurill',
    'Wynaut',
    'Chingling',
    'Bonsly',
    'Mime Jr.',
    'Munchlax',
    'Mantyke',
    // Eterna City Egg only has these ones
    'Riolu',
    'Budew',
    'Happiny',
    'Togepi',
  ],
  'coro-5': ['Turtwig', 'Chimchar', 'Piplup'],
  'coro-7': ['Bulbasaur', 'Charmander', 'Squirtle', 'Wobbuffet'],
  'coro-10': ['Treecko', 'Torchic', 'Mudkip', 'Beldum'],
  'coro-11': ['Omanyte', 'Kabuto', 'Lileep', 'Anorith', 'Shieldon', 'Cranidos', 'Aerodactyl'],
  'coro-13': ['Crystal Onix'],
  'coro-14': ['Chikorita', 'Cyndaquil', 'Totodile'],
  'coro-108': ['Porygon'],
  'coro-20': ['Stitched Gengar', 'Rotom'],
  'coro-22': ['Gabite'],
  'coro-27': [
    // Trainer School Egg has every baby here
    'Pichu',
    'Cleffa',
    'Igglybuff',
    'Smoochum',
    'Tyrogue',
    'Smoochum',
    'Elekid',
    'Magby',
    'Azurill',
    'Wynaut',
    'Chingling',
    'Bonsly',
    'Mime Jr.',
    'Munchlax',
    'Mantyke',
    // Eterna City Egg only has these ones
    'Riolu',
    'Budew',
    'Happiny',
    'Togepi',
  ],
  'coro-28': ['Spiritomb'],
  'coro-29': ['Ditto'],
  'coro-31': ['Litwick'],
  'coro-41': ['Pichu'],
  'coro-49': ['Azelf'],
  'coro-55': ['Uxie'],
  'coro-56': ['Dialga', 'Palkia'],
  'coro-62': ['Lapras'],
  'coro-63': [
    'Zubat',
    'Psyduck',
    'Machop',
    'Geodude',
    'Murkrow',
    'Bidoof',
    'Kricketot',
    'Shinx',
    'Budew',
    'Pachirisu',
    'Buneary',
    'Lickitung',
    'Magnemite',
    'Rhyhorn',
    'Houndoom',
    'Swablu',
    'Absol',
    'Golbat',
    'Hoothoot',
    'Bibarel',
    'Chingling',
    'Stunky',
    'Skuntank',
    'Machoke',
    'Graveler',
    'Aipom',
    'Wingull',
    'Munchlax',
    'Purugly',
    'Pelipper',
    'Luxio',
    'Glameow',
    'Mantyke',
    'Wurmple',
    'Silcoon',
    'Roselia',
    'Combee',
    'Cherubi',
    'Scyther',
    'Pinsir',
    'Buizel',
    'Shellos',
    'Gastrodon',
    'Togepi',
    'Ralts',
    'Barboach',
    'Wooper',
    'Quagsire',
    'Tentacool',
    'Tentracruel',
    'Gible',
    'Octillery',
    'Whiscash',
    'Gabite',
    'Onix',
    'Skorupi',
    'Gligar',
    'Teddiursa',
    'Bronzor',
    'Hippopotas',
    'Magby',
    'Ponyta',
    'Croagunk',
    'Swinub',
    'Gastly',
    'Misdreavus',
    'Smoochum',
    'Elekid',
    'Duskull',
    'Meditie',
    'Kadabra',
    'Girafarig',
    'Mr. Mime',
    'Snorunt',
    'Glalie',
    'Sneasel',
    'Snover',
  ],
  'coro-65': ['Manaphy'],
  'coro-68': [],
  'coro-78': [],
  'coro-79': [],
  'coro-84': ['Articuno'],
  'coro-85': ['Zapdos'],
  'coro-86': ['Moltres'],
  'coro-87': ['Mewtwo'],
  'coro-88': ['Raikou'],
  'coro-89': ['Entei'],
  'coro-90': ['Suicune'],
  'coro-91': ['Lugia'],
  'coro-92': ['Ho-Oh'],
  'coro-93': ['Celebi'],
  'coro-94': ['Regirock', 'Registeel', 'Regice', 'Regigigas'],
  'coro-95': ['Latios', 'Latias', 'Cresselia'],
  'coro-96': ['Kyogre'],
  'coro-97': ['Groudon'],
  'coro-98': ['Rayquaza'],
  'coro-99': ['Jirachi'],
  'coro-100': ['Deoxys'],
  'coro-101': ['Mesprit'],
  'coro-102': ['Heatran'],
  'coro-103': ['Giratina'],
  'coro-104': ['Darkrai'],
  'coro-105': ['Shaymin'],
  'coro-106': ['Arceus'],
  'coro-107': ['Tinkatuff'],
};

const wildEncounters: EncounterTable = coronet_data;

const COR_ENC: EncounterTable = {
  ...staticEncounters,
  ...wildEncounters,
};

export default COR_ENC;
